In [8]:
import numpy as np
import logging
from pca import PCA

logging.basicConfig()
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

In [9]:
X = np.array([[4.0, 4.2, 3.9, 4.3, 4.1], [2.0, 2.1, 2.0, 2.1, 2.2], [0.60, 0.59, 0.58, 0.62, 0.63]])
PCA.principal_component(X)

array([ 0.93676841,  0.34958469, -0.0159843 ])

In [3]:
class PCA(object):
    @staticmethod
    def cov_mat(X):
        """Objects of this class is a Principal component.

       Examples
       --------
       >>> import numpy as np
       >>> X = np.array([[1,2,3,4,5], [2,3,6,9,0], [8,1,6,4,3]])

       Parameter
       -------------
       X : A numpy array
       """
        row_X, size_row_X = np.shape(X)
        X_mean0 = np.empty(shape=np.shape(X))
        temp_list = list()

        """
         Variables:
         ---------
         row_X: number of lists in the input data X
         size_row_X: number of elements in each each lists
         X_mean0 : The transformed X when subtracted from mean
        """
        for i in range(row_X):
            mean_i = (np.sum(X[i]))/size_row_X
            for j in X[i]:
                j = j - mean_i
                temp_list.append(j)
            X_mean0[i] = temp_list
            temp_list = []
        print(X_mean0)
        cov_matrix = np.dot(X_mean0, X_mean0.T)/(size_row_X - 1)
        print(row_X)
        
        return cov_matrix

    def principal_component(X):
        Y = PCA.cov_mat(X)
        print(Y, "cov")
        eigen_val, eigen_vec = np.linalg.eig(Y)
        """ eigenvalue and eigen vectors are extracted through a
         square matrix which is the covariance matrix in our case.
         Variables:
         ---------
         eigen_val: eignevalue of the input data X
         eigen_vec: eignenvector of the input data X
        """
        maximum = np.max(eigen_val)
        index_pc = eigen_val.tolist().index(maximum)
        print(eigen_val)
        print(eigen_vec)
        return eigen_vec[index_pc]

In [4]:
X = np.array([[4.0, 4.2, 3.9, 4.3, 4.1], [2.0, 2.1, 2.0, 2.1, 2.2], [0.60, 0.59, 0.58, 0.62, 0.63]])
PCA.principal_component(X)

[[-0.1    0.1   -0.2    0.2    0.   ]
 [-0.08   0.02  -0.08   0.02   0.12 ]
 [-0.004 -0.014 -0.024  0.016  0.026]]
3
[[0.025   0.0075  0.00175]
 [0.0075  0.007   0.00135]
 [0.00175 0.00135 0.00043]] cov
[0.02787694 0.00439387 0.0001592 ]
[[ 0.93676841  0.34958469 -0.0159843 ]
 [ 0.34148069 -0.92313136 -0.1766902 ]
 [ 0.0765238  -0.16005947  0.98413672]]


array([ 0.93676841,  0.34958469, -0.0159843 ])

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [6]:
print(pca.singular_values_)

[5.55408017 0.10981844]


In [7]:
print(pca.explained_variance_ratio_)

[9.99609198e-01 3.90801764e-04]
